### ISSUE TITLE
安装好报错

### ISSUE THREAD

**Issue by jyeric** [ouuan/fake-luogu-paintboard-server#2]
安装时使用淘宝镜像，在Windows 10 上安装。

安装命令：
```
C:\Users\jyeri>npm install -g fake-luogu-paintboard-server
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
C:\nodejs\fake-luogu-paintboard-server -> C:\nodejs\node_modules\fake-luogu-paintboard-server\cmd.js
npm WARN ws@7.4.1 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.4.1 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.

+ fake-luogu-paintboard-server@3.0.2
added 214 packages from 136 contributors in 14.14s
```
执行命令：
```
C:\Users\jyeri>fake-luogu-paintboard-server --help

C:\nodejs\node_modules\fake-luogu-paintboard-server\lib.js:115
    const uid = ctx.cookies?._uid;
                            ^

SyntaxError: Unexpected token '.'
[90m    at wrapSafe (internal/modules/cjs/loader.js:1067:16)[39m
[90m    at Module._compile (internal/modules/cjs/loader.js:1115:27)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:1000:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:899:14)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:1040:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:72:18)[39m
    at Object.<anonymous> (C:\nodejs\node_modules\[4mfake-luogu-paintboard-server[24m\cmd.js:22:26)
[90m    at Module._compile (internal/modules/cjs/loader.js:1151:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)[39m
```

**Comment by ouuan** [comment]
请使用最新版本的 Node.js
